# This file was generated by GoReleaser. DO NOT EDIT.
cask "bs" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args:           ["-d", "com.apple.quarantine", "bs"],
          chdir:          ".",
          writable_paths: ["bs"],
          must_succeed:   false
    end
  end

  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "8560e84c16c35fc4193780a1d693239af5e77e1bee9abd2d90253b0f1b2aae84"
      url "https://github.com/smithbr/bside/releases/download/v#{version}/bside_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b3ecc9acb5a2aadd4810c8e7328841644e91e82b7cbe7adbbff42e9542b693d1"
      url "https://github.com/smithbr/bside/releases/download/v#{version}/bside_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a313ad8efcd1188906fe12315882a7c341548d69152f982d29784ad62bde2f54"
      url "https://github.com/smithbr/bside/releases/download/v#{version}/bside_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f2f045693ee0cc20d4b90465af59050b0cce541f15c83217d6aeb3cbf64ab32c"
      url "https://github.com/smithbr/bside/releases/download/v#{version}/bside_#{version}_linux_amd64.tar.gz"
    end
  end

  name "bs"
  desc "Turn a song link into links for the other streaming apps"
  homepage "https://github.com/smithbr/bside"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bs"

  # No zap stanza required
end
