# This file was generated by GoReleaser. DO NOT EDIT.
cask "bs" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "920d794ba6b3b82a595575dbfec59b766e180a800ae5ded372bebf01efd9f1a6"
      url "https://github.com/smithbr/bside/releases/download/v#{version}/bside_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d5f05dfcdbff2aea8a041ca2bee7259735761bed1848711dcea9cd972ff9b049"
      url "https://github.com/smithbr/bside/releases/download/v#{version}/bside_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d89c09d300fb5b494d3686460fb333818807a0735433cdfa8638d96d32edb7cf"
      url "https://github.com/smithbr/bside/releases/download/v#{version}/bside_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9f2de2a3affa1311564cd5634fb815927f3b54b26c57f87e6610ea74faa4eaf1"
      url "https://github.com/smithbr/bside/releases/download/v#{version}/bside_#{version}_linux_amd64.tar.gz"
    end
  end

  name "bs"
  desc "Turn a song link into links for the other streaming apps"
  homepage "https://github.com/smithbr/bside"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bs"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bs"]
    end
  end

  # No zap stanza required
end
